# Generated by Django 3.2.5 on 2021-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=None),
        ),
    ]
