# Generated by Django 3.2.5 on 2021-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_companydetails_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PREMIUM', 'PREMIUM')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='vat_id',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='street',
            field=models.TextField(max_length=255),
        ),
    ]
