# Generated by Django 3.2.5 on 2021-09-13 07:49

from django.db import migrations, models

def set_account_type(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if user.is_company and user.is_admin:
            user.account_type = 'PREMIUM'
        else:
            user.account_type = 'FREE'
        user.save()

def delete_account_type(apps, schema_editor):
    Person = apps.get_model("users", "User")
    for user in User.objects.all():
        user.account_type = None
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210913_0737'),
    ]

    operations = [
        migrations.RunPython(set_account_type, reverse_code=delete_account_type)

    ]
