# Generated by Django 3.2.5 on 2021-09-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210913_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PREMIUM', 'PREMIUM')], max_length=10),
        ),
    ]
