# Generated by Django 3.2.5 on 2021-09-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.IntegerField(default=None)),
                ('name', models.TextField(default=None, max_length=255)),
                ('price', models.IntegerField(default=None)),
            ],
        ),
    ]
