# Generated by Django 3.2.5 on 2021-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
