# Generated by Django 3.2.5 on 2021-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
