# Generated by Django 3.2.5 on 2021-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
