# Generated by Django 3.2.5 on 2021-09-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210915_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
