# Generated by Django 3.2.5 on 2021-09-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_total',
            field=models.IntegerField(null=True),
        ),
    ]
